---
title: "HW3, Rebecca Brink and Chad Melton"
output: github_document
---
```
<style type="text/css">
    ol { list-style-type: upper-alpha; }
</style>
```

```{r}
library(epiR)
library(ggplot2)
library(vcdExtra)
library(vcd)
library(MASS)
library(lmtest)
```


## 3.13

a)

```{r}

crab = read.csv("C:\\Users\\chadm\\OneDrive\\Documents\\StatsData\\crab.csv",header=TRUE)

crab.model = glm(satell~weight,data=crab,family = poisson(link ="log"))
summary(crab.model)

```

The equation is: log(muHat) = -0.42841 + 0.58930x


```{r}
x=2.44

muHat = exp(-0.42841 + 0.58930*x)
```

The mean Y for female crabs of average weight 2.44 kg is 2.744179.



## Including Code

You can include R code in the document as follows:

```{r}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
